datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-1-ap-northeast-1.cz8ibqhhlera.ap-northeast-1.rds.amazonaws.com:5432/postgres
    username: postgres22
    password: postgres
